Add Crystal Haskell Julia and Raku bindings

diff --git a/util/release b/util/release
--- a/util/release
+++ b/util/release
@@ -576,6 +576,70 @@ do-release-lua() (
   luarocks upload --api-key "$LUAROCKS_API_KEY" "yamlstar-$VERSION-1.rockspec"
 )
 
+# Crystal - publish split repository
+do-release-crystal() (
+  echo 'Publishing Crystal binding repository...'
+  ../util/release-crystal
+)
+
+# Haskell - publish to Hackage
+do-release-haskell() (
+  echo 'Publishing Haskell package to Hackage...'
+  HACKAGE_TOKEN=${HACKAGE_TOKEN:-}
+  if [[ -z $HACKAGE_TOKEN && -f ~/.yamlstar-secrets.yaml ]]; then
+    HACKAGE_TOKEN=$(ys -e '(.haskell.token || .hackage.token):say' ~/.yamlstar-secrets.yaml)
+  fi
+  [[ $HACKAGE_TOKEN ]] ||
+    die 'ERROR: HACKAGE_TOKEN not set and ~/.yamlstar-secrets.yaml not found'
+
+  make dist
+  cabal upload \
+    --publish \
+    --verbose \
+    --token="$HACKAGE_TOKEN" \
+    "dist-newstyle/sdist/yamlstar-$VERSION.0.tar.gz"
+)
+
+# Julia - request registration with JuliaRegistrator
+do-release-julia() (
+  echo 'Requesting Julia package registration...'
+  local gh_token
+  gh_token=${GH_TOKEN:-${GITHUB_TOKEN:-}}
+  if [[ -z $gh_token && -f ~/.yamlstar-secrets.yaml ]]; then
+    gh_token=$(ys -e '(.julia.token || .github.token):say' ~/.yamlstar-secrets.yaml)
+  fi
+  [[ $gh_token ]] ||
+    die 'ERROR: GH_TOKEN/GITHUB_TOKEN not set and ~/.yamlstar-secrets.yaml not found'
+
+  local head_commit
+  head_commit=$(git -C .. rev-parse HEAD)
+  curl -L -X POST \
+    -H 'Accept: application/vnd.github+json' \
+    -H "Authorization: Bearer $gh_token" \
+    -H 'X-GitHub-Api-Version: 2022-11-28' \
+    "https://api.github.com/repos/yaml/yamlstar/commits/$head_commit/comments" \
+    -d '{"body":"@JuliaRegistrator register subdir=julia\n"}'
+)
+
+# Raku - publish to fez/zef
+do-release-raku() (
+  echo 'Publishing Raku package to fez...'
+  make raku-install
+
+  if [[ -n ${FEZ_TOKEN:-} && -n ${FEZ_USER:-} ]]; then
+    mkdir -p "$HOME"
+    printf '{"un":"%s","key":"%s"}\n' "$FEZ_USER" "$FEZ_TOKEN" > "$HOME/.fez-config.json"
+  elif [[ -f ~/.yamlstar-secrets.yaml ]]; then
+    FEZ_USER=$(ys -e '(.raku.user || .fez.user):say' ~/.yamlstar-secrets.yaml 2>/dev/null || true)
+    FEZ_TOKEN=$(ys -e '(.raku.token || .fez.token):say' ~/.yamlstar-secrets.yaml 2>/dev/null || true)
+    if [[ $FEZ_USER && $FEZ_TOKEN ]]; then
+      printf '{"un":"%s","key":"%s"}\n' "$FEZ_USER" "$FEZ_TOKEN" > "$HOME/.fez-config.json"
+    fi
+  fi
+
+  fez upload
+)
+
 # PHP - publish split repository and notify Packagist
 do-release-php() (
   echo 'Publishing PHP package repo and notifying Packagist...'
